// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/api/telemetry.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage       float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage    uint64                 `protobuf:"varint,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	NetworkTxBytes uint64                 `protobuf:"varint,3,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	NetworkRxBytes uint64                 `protobuf:"varint,4,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	AgentId        string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CollectedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	MemoryPercent  float64                `protobuf:"fixed64,7,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	LoadAvg_1      float64                `protobuf:"fixed64,8,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5      float64                `protobuf:"fixed64,9,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15     float64                `protobuf:"fixed64,10,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	DiskReadBytes  uint64                 `protobuf:"varint,11,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes uint64                 `protobuf:"varint,12,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_pkg_api_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_pkg_api_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Metric) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Metric) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *Metric) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *Metric) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Metric) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *Metric) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *Metric) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *Metric) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *Metric) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *Metric) GetDiskReadBytes() uint64 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *Metric) GetDiskWriteBytes() uint64 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

var File_pkg_api_telemetry_proto protoreflect.FileDescriptor

const file_pkg_api_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/telemetry.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x03\n" +
	"\x06Metric\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x04R\vmemoryUsage\x12(\n" +
	"\x10network_tx_bytes\x18\x03 \x01(\x04R\x0enetworkTxBytes\x12(\n" +
	"\x10network_rx_bytes\x18\x04 \x01(\x04R\x0enetworkRxBytes\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12=\n" +
	"\fcollected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12%\n" +
	"\x0ememory_percent\x18\a \x01(\x01R\rmemoryPercent\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\b \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\t \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\n" +
	" \x01(\x01R\tloadAvg15\x12&\n" +
	"\x0fdisk_read_bytes\x18\v \x01(\x04R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\f \x01(\x04R\x0ediskWriteBytes2<\n" +
	"\tTelemetry\x12/\n" +
	"\rStreamMetrics\x12\v.api.Metric\x1a\v.api.Metric\"\x00(\x010\x01B\tZ\apkg/apib\x06proto3"

var (
	file_pkg_api_telemetry_proto_rawDescOnce sync.Once
	file_pkg_api_telemetry_proto_rawDescData []byte
)

func file_pkg_api_telemetry_proto_rawDescGZIP() []byte {
	file_pkg_api_telemetry_proto_rawDescOnce.Do(func() {
		file_pkg_api_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_telemetry_proto_rawDesc), len(file_pkg_api_telemetry_proto_rawDesc)))
	})
	return file_pkg_api_telemetry_proto_rawDescData
}

var file_pkg_api_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_api_telemetry_proto_goTypes = []any{
	(*Metric)(nil),                // 0: api.Metric
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pkg_api_telemetry_proto_depIdxs = []int32{
	1, // 0: api.Metric.collected_at:type_name -> google.protobuf.Timestamp
	0, // 1: api.Telemetry.StreamMetrics:input_type -> api.Metric
	0, // 2: api.Telemetry.StreamMetrics:output_type -> api.Metric
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_telemetry_proto_init() }
func file_pkg_api_telemetry_proto_init() {
	if File_pkg_api_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_telemetry_proto_rawDesc), len(file_pkg_api_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_telemetry_proto_goTypes,
		DependencyIndexes: file_pkg_api_telemetry_proto_depIdxs,
		MessageInfos:      file_pkg_api_telemetry_proto_msgTypes,
	}.Build()
	File_pkg_api_telemetry_proto = out.File
	file_pkg_api_telemetry_proto_goTypes = nil
	file_pkg_api_telemetry_proto_depIdxs = nil
}
